services:
  # PostgreSQL Database
  - type: pserv
    name: project-2-db
    plan: free
    databaseName: project_2
    databaseUser: project_2
    region: singapore

  # Backend Web Service (Docker)
  - type: web
    name: project-2-backend
    runtime: docker
    region: singapore
    plan: free
    branch: update/deployment
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: project-2-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    autoDeploy: true
