tags:
  - name: Images
    description: 이미지 관련 API

paths:
  /images/upload:
    post:
      tags:
        - Images
      summary: 이미지 업로드
      description: 이미지를 서버에 업로드하고 이미지 URL을 반환합니다.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 업로드할 이미지 파일
      responses:
        '200':
          description: 이미지 업로드 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    format: uri
                    example: 'https://res.cloudinary.com-image-name.png'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse_BadRequest'
